import 'dart:async'; import '../models/api_result.dart'; import '../models/authentication.dart'; import '../models/chat_message.dart'; import '../models/conversation.dart'; import '../models/file_models.dart'; import '../models/page_result.dart'; import '../models/user.dart'; import 'authentication_repository.dart'; import 'chat_repository.dart'; import 'file_repository.dart'; import '../services/contracts.dart'; import '../services/mock_services.dart';
class MockAuthenticationRepository implements AuthenticationRepository { MockAuthenticationRepository(this._tokens); final TokenStorageService _tokens; User? _user; @override Future<ApiResult<AuthenticationOutcome>> signIn({required String identifier,required String password})async { if(identifier.trim().isEmpty||password.isEmpty)return const ApiFailure(ApiError(ApiErrorKind.unknown,'Enter your credentials')); _user=const User(id:'current-user',displayName:'Team Member',email:'member@example.invalid'); final auth=Authenticated(_user!,const AuthTokens(accessToken:'mock-session-token'));await _tokens.write(auth.tokens);return ApiSuccess(auth); } @override Future<ApiResult<Authenticated>> verifyMfa({required String challengeId,required String code})async=>const ApiFailure(ApiError(ApiErrorKind.unknown,'Mock sign-in does not require MFA')); @override Future<User?> currentUser()async=>_user; @override Future<void> signOut()async{_user=null;await _tokens.clear();} }
class MockChatRepository implements ChatRepository {
 MockChatRepository({OutboxService? outbox, ConnectivityService? connectivity, RealtimeService? realtime}) : _outbox=outbox ?? MemoryOutboxService(), _connectivity=connectivity ?? MockConnectivityService(), _realtime=realtime ?? MockRealtimeService();
 final OutboxService _outbox; final ConnectivityService _connectivity; final RealtimeService _realtime; StreamSubscription<RealtimeEvent>? _subscription; final _incoming=StreamController<ChatMessage>.broadcast();
 @override Stream<ChatMessage> get incomingMessages=>_incoming.stream;
 @override Future<void> initialize() async {_subscription ??= _realtime.events.listen((e){if(e is MessageReceived)_incoming.add(e.message);}); await _realtime.connect();}
 @override Future<void> dispose() async {await _subscription?.cancel(); await _realtime.disconnect(); await _incoming.close();}
 final _conversations=<Conversation>[Conversation(id:'team',title:'General',kind:ConversationKind.group,lastMessagePreview:'Welcome to the team chat',lastActivityAt:DateTime(2026,1,2),unreadCount:2),Conversation(id:'design',title:'Product Design',kind:ConversationKind.group,lastMessagePreview:'The latest mockups are ready',lastActivityAt:DateTime(2026,1,1)),Conversation(id:'direct',title:'Alex Morgan',kind:ConversationKind.direct,lastMessagePreview:'Thanks!',lastActivityAt:DateTime(2025,12,31))];
 final _messages=<String,List<ChatMessage>>{};
 @override Future<ApiResult<PageResult<Conversation>>> conversations(PageRequest request)async=>ApiSuccess(PageResult(items:List.unmodifiable(_conversations)));
 @override Future<ApiResult<PageResult<ChatMessage>>> messages(String id,PageRequest request)async=>ApiSuccess(PageResult(items:List.unmodifiable(_messages[id]??[])));
 @override Future<ApiResult<ChatMessage>> sendMessage({required String conversationId,required String body,required String clientId})async { final pending=ChatMessage(id:clientId,conversationId:conversationId,senderId:'current-user',senderDisplayName:'You',body:body,sentAt:DateTime.now(),status:MessageDeliveryStatus.pending); if(!await _connectivity.isOnline){await _outbox.enqueue(pending);return ApiSuccess(pending);} final m=ChatMessage(id:'mock-$clientId',conversationId:conversationId,senderId:'current-user',senderDisplayName:'You',body:body,sentAt:DateTime.now());(_messages[conversationId]??=[]).add(m);return ApiSuccess(m); }
}
class MockFileRepository implements FileRepository { @override Future<ApiResult<UploadedFile>> upload(FileSelection file)async=>ApiSuccess(UploadedFile(id:'mock-file-${file.name.hashCode}',name:file.name)); }
